sudo: required
language: cpp
compiler:
  - gcc
  - clang

env:
  - THENEEDFORTHIS=FAIL

branches:
  except:
    - debian
    - nightly/debian
    - nightly/ubuntu
    - ubuntu

matrix:
  include:
    - env: QTTYPE=4
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_install: bash ./travis/before_install.sh
install: bash ./travis/install.sh

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

before_script: bash ./travis/before_script.sh
script: bash ./travis/script.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#tora"
    on_failure: always
    on_success: change
